apiVersion: v1
kind: Secret
metadata:
  name: operator-config
type: Opaque
stringData:
  operator-config.json: |-
    {
      "Type": "asm",
      "Parameters": {
        "accessKeyID": "$AWS_ACCESS_KEY_ID",
        "region": "$AWS_DEFAULT_REGION",
        "secretAccessKey": "$AWS_SECRET_ACCESS_KEY"
      }
    }
